name: bullet

services:

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://jecmui:test@db:5432/bullet_db
    command: npm start
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jecmui
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bullet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bullet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: