// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/in": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/in";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "./layouts/auth.tsx": {
    id: "layouts/auth";
    page: "/in";
  };
  "routes/bulletin.tsx": {
    id: "routes/bulletin";
    page: "/in";
  };
};